# Generated by Django 6.0.3 on 2026-03-20 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Categoria')),
            ],
            options={
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('resumo', models.TextField(max_length=500, verbose_name='Resumo (Aparece na Home)')),
                ('conteudo', models.TextField(verbose_name='Conteúdo Completo')),
                ('imagem', models.ImageField(upload_to='noticias/', verbose_name='Imagem da Destaque')),
                ('data_publicacao', models.DateTimeField(auto_now_add=True, verbose_name='Postado em')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noticias', to='news.categoria', verbose_name='Categoria')),
            ],
            options={
                'ordering': ['-data_publicacao'],
            },
        ),
    ]
